Feature/en 295 company to kyc
envoys-lab/envoys-frontend pull request #61
Opened 2022-04-17 20:21 UTC by AntonCodyua

2022-04-17 20:41 UTC, Ekkana approved these changes

2022-04-18 10:14 UTC, kdementiev-reinvently requested changes

2022-04-18 10:14 UTC, kdementiev-reinvently commented on src/state/companyTokens/reducer.ts
> +          chainId: ChainId.MAINNET,
Please, set chainID from config. Use parameter - CURRENT_CHAIN_ID

2022-04-18 12:25 UTC, Ekkana commented on src/state/companyTokens/reducer.ts
> +          chainId: ChainId.MAINNET,
Fixed

2022-04-18 12:51 UTC, Ekkana approved these changes

2022-04-18 12:58 UTC, merged